<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sub_Copyright www.mybatis.org</name>
   <tag></tag>
   <elementGuidId>44ca821f-8e31-4001-9690-d446cf061e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sub</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Content']/p[2]/sub</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Copyright www.mybatis.org&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>sub</value>
      <webElementGuid>54ea21a7-e6d1-403b-bb78-7264dce08ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copyright www.mybatis.org </value>
      <webElementGuid>99e5eba4-2004-4123-87a6-686965f3e5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Content&quot;)/p[2]/sub[1]</value>
      <webElementGuid>895957e6-5891-44cd-b6c2-029cf4efa45c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/p[2]/sub</value>
      <webElementGuid>5dddf059-f24a-4b65-a614-d3d2fe5e4b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the Store'])[1]/following::sub[1]</value>
      <webElementGuid>deded1e1-37c5-458e-a147-0ab4884c4813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to JPetStore 6'])[1]/following::sub[1]</value>
      <webElementGuid>289fcf48-66fc-49f6-871d-9b6425c2c8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copyright www.mybatis.org']/parent::*</value>
      <webElementGuid>a3c148d2-70f4-48cc-934c-1187a5a76144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sub</value>
      <webElementGuid>444e29e0-4f43-46ef-937a-c21c73bab546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//sub[(text() = 'Copyright www.mybatis.org ' or . = 'Copyright www.mybatis.org ')]</value>
      <webElementGuid>2178d8d7-bce2-4334-8c8d-75d402410a39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
